from crewai import Crew, Process
from agents import researcher, blog_writer
from tasks import research_task, blog_task

my_crew = Crew(
    agents=[researcher, blog_writer],
    tasks=[research_task, blog_task],
    process=Process.sequential,
    verbose=True
)

result = my_crew.kickoff()

# Save result to HTML
html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AI Blog Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background-color: #f4f6f9;
            margin: 40px;
            color: #333;
        }}
        .container {{
            max-width: 800px;
            margin: auto;
            background: #fff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0,0,0,0.1);
        }}
        h1 {{
            text-align: center;
            color: #2c3e50;
        }}
        pre {{
            white-space: pre-wrap;
            word-wrap: break-word;
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            border: 1px solid #ddd;
            font-size: 14px;
            line-height: 1.6;
        }}
        footer {{
            text-align: center;
            margin-top: 20px;
            font-size: 12px;
            color: #888;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>AI Blog Report</h1>
        <pre>{result}</pre>
        <footer>Generated by CrewAI Blog Workflow</footer>
    </div>
</body>
</html>
"""

with open("report.html", "w", encoding="utf-8") as f:
    f.write(html_content)

print("Report saved as report.html")
